package com.oceanview.controller;

import com.oceanview.dao.GuestDAOImpl;
import com.oceanview.dao.ReservationDAOImpl;
import com.oceanview.model.Guest;
import com.oceanview.model.Reservation;
import com.oceanview.service.BillingService;

// IMPORTANT: Change "javax" to "jakarta" if you are using Tomcat 10 or newer!
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.sql.Date;

/**
 * Controller to handle the creation of new reservations and guest registration.
 */
@WebServlet("/AddReservationServlet")
public class AddReservationServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    private GuestDAOImpl guestDAO;
    private ReservationDAOImpl reservationDAO;
    private BillingService billingService;

    @Override
    public void init() throws ServletException {
        super.init();
        // Initialize our Data Access Objects and Service layer
        guestDAO = new GuestDAOImpl();
        reservationDAO = new ReservationDAOImpl();
        billingService = new BillingService();
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        // 1. Security Check: Ensure the user is still logged in securely
        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("loggedUser") == null) {
            response.sendRedirect("login.jsp?error=Session expired. Please log in again.");
            return;
        }

        try {
            // 2. Extract Guest Details from the HTML form
            String fullName = request.getParameter("fullName");
            String contactNumber = request.getParameter("contactNumber");
            String address = request.getParameter("address");

            // 3. Extract Reservation Details from the HTML form
            int roomId = Integer.parseInt(request.getParameter("roomId"));
            Date checkInDate = Date.valueOf(request.getParameter("checkInDate"));
            Date checkOutDate = Date.valueOf(request.getParameter("checkOutDate"));

            // 4. Determine Room Rate (Mapping to our MySQL 'rooms' table rates)
            double ratePerNight = 0.0;
            switch (roomId) {
                case 1: ratePerNight = 5000.00; break; // Standard Single
                case 2: ratePerNight = 7500.00; break; // Standard Double
                case 3: ratePerNight = 12000.00; break; // Deluxe Ocean View
                case 4: ratePerNight = 25000.00; break; // Presidential Suite
                default: throw new IllegalArgumentException("Invalid room type selected.");
            }

            // 5. Business Logic: Calculate total bill using our dedicated Service class
            double totalCost = billingService.calculateTotalCost(checkInDate, checkOutDate, ratePerNight);

            // 6. --- THE INTEGRATION ---
            // Create the Guest object and save them to the database FIRST
            Guest newGuest = new Guest(0, fullName, address, contactNumber);
            int generatedGuestId = guestDAO.saveAndReturnId(newGuest);

            // Verify the guest was saved successfully before proceeding
            if (generatedGuestId <= 0) {
                response.sendRedirect("add-reservation.jsp?error=Failed to register guest details in the system.");
                return;
            }

            // 7. Build the Reservation object using the REAL Guest ID we just got from MySQL
            Reservation newReservation = new Reservation(
                0, // ID is auto-generated by MySQL
                generatedGuestId,
                roomId,
                checkInDate,
                checkOutDate,
                totalCost,
                "CONFIRMED"
            );

            // 8. Save the linked reservation to the database
            boolean isSaved = reservationDAO.save(newReservation);

            if (isSaved) {
                // Success! Redirect back to the dashboard
                response.sendRedirect("dashboard.jsp?success=Reservation successfully created!");
            } else {
                // Failure during reservation insertion
                response.sendRedirect("add-reservation.jsp?error=Database error. Could not save the reservation details.");
            }

        } catch (IllegalArgumentException e) {
            // Catches date validation errors (e.g., checkout before check-in) thrown by the BillingService
            response.sendRedirect("add-reservation.jsp?error=" + e.getMessage());
        } catch (Exception e) {
            // Catch-all for parsing errors (like invalid date formats)
            e.printStackTrace();
            response.sendRedirect("add-reservation.jsp?error=Invalid form data submitted. Please check your inputs.");
        }
    }
}